name: ML Training Pipeline

# Add permissions block at the top level
permissions:
  checks: write
  contents: read
  pull-requests: write

on:
  push:
    branches: [ master]

jobs:
  train:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Train model
      run: |
        python src/train.py
        
    - name: Run tests
      run: |
        python -m pytest tests/ --junitxml=test-results.xml -v
        
    - name: Publish Test Results
      uses: EnricoMi/publish-unit-test-result-action@v2
      if: always()
      with:
        files: test-results.xml
        
    - name: Upload model artifacts
      uses: actions/upload-artifact@v3
      with:
        name: trained-model
        path: models/
        retention-days: 5